### ISSUE TITLE
Incompatible with some SVGO output

### ISSUE THREAD

**Issue by bfred-it** [jkroso/parse-svg-path#1]
This path is reported as "malformed path data", but [hughsk/svg-path-parser](https://github.com/hughsk/svg-path-parser) parses it without errors

    M.157 15.32c-.105-.1-.157-.18-.157-.23 0-.057.063-.147.19-.262.595-1.882 5.684-8.786 14.875-8.786 9.798 0 14.935 7.846 14.935 9.09 0 1.244-5.137 9.09-14.935 9.09-9.39 0-14.5-7.207-14.908-8.902zm0 0c.93.895 5.97 3.49 14.778 3.49 9.798 0 14.935-3.21 14.935-3.72 0-.51-5.137-3.72-14.935-3.72-8.71 0-13.737 2.537-14.746 3.458-.04.124-.06.227-.06.304 0 .052.01.115.027.188z

**Comment by soswow** [comment]
Yeah, when I read http://www.w3.org/TR/SVG/paths.html#PathData I understood it's not as simple and decided to look for solution that can handle exactly this example )

**Comment by Sphinxxxx** [comment]
The problem is that the regex in `parseValues()` gets confused by decimal numbers with no spaces between, e.g. `.052.01.115.027.188`. I propose two alternatives to fix this:

1. Before the regex matching, alter the input string to add a space between such numbers before: `args = args.replace(/(\.\d+)(?=\.)/g, '$1 ');`

1. Change the regex pattern itself (tested only with @bfred-it's example): `args = args.match(/-?[0-9]*\.?[0-9]+(?:e[-+]?\d+)?/ig);`

Test: https://jsfiddle.net/b28cu6ac/

**Comment by jkroso** [comment]
I'd favour option 2
